### ISSUE TITLE
Tuple unpacking breaks this plugin

### ISSUE THREAD

**Issue by sobolevn** [gforcada/flake8-builtins#40]
## Code

Valid `python` code break this linter with an exception.

```pycon
>>> a, *(b, c) = 1, 2, 3
>>> print(a, b, c)
1 2 3
```

## Problem

Reproduction:

```python
# test.py
a, *(b, c) = 1, 2, 3
```

Run: `flake8 test.py`
Output:

```
» flake8 test.py
Traceback (most recent call last):
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.7/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.7/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.7/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.7/site-packages/flake8/checker.py", line 331, in run
    self.run_serial()
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.7/site-packages/flake8/checker.py", line 315, in run_serial
    checker.run_checks()
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.7/site-packages/flake8/checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.7/site-packages/flake8/checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.7/site-packages/flake8_builtins.py", line 106, in run
    for line, offset, msg, rtype in value:
  File "/Users/sobolev/Documents/github/wemake-python-styleguide/.venv/lib/python3.7/site-packages/flake8_builtins.py", line 124, in check_assignment
    item.value.id in BUILTINS:
AttributeError: 'Tuple' object has no attribute 'id'
```

Versions:
- python3.7
- flake8: 3.7.8
- flake8-builtins: 1.4.1

**Comment by sobolevn** [comment]
@gforcada the problem is in these lines:

```python
            elif PY3 and \
                    isinstance(item, ast.Starred) and \
                    item.value.id in BUILTINS:
```

`ast.Starred` in this case contains `Union[ast.Name, ast.Tuple]`, not just `ast.Name`.
We can write a helper like this one: https://github.com/wemake-services/wemake-python-styleguide/blob/b0421a967d7e34a2998127c78a17887e9cc622dd/wemake_python_styleguide/logic/naming/name_nodes.py#L64-L109 to fetch names from assigns.

You can just copy-paste the code if it does solve this problem.

**Comment by gforcada** [comment]
@sobolevn thanks for the report and for finding a solution already! :100: may I ask if you could do a pull request already? :thinking: TIA

**Comment by sobolevn** [comment]
@gforcada sorry, but I am out of capacity. Working 12 hours per day, including weekends 🙂

**Comment by gforcada** [comment]
Oh wow, then, all the more to thank you for the report! I will try to find time to get that in myself :+1:

**Comment by sobolevn** [comment]
@gforcada hi, how's it going? I might have some time to help you with this one if that's fine.

**Comment by gforcada** [comment]
@sobolevn :sweat: sorry, I totally missed this one :confused: any help is much appreciated, thanks for the friendly reminder! :sparkles: if you have the time/capacity to create a pull request that would be awesome :rainbow: :unicorn: :+1:

**Comment by sobolevn** [comment]
Awesome! Thanks a lot! @gforcada can you please make a release?

**Comment by gforcada** [comment]
@sobolevn :sweat_smile: just done it :+1: `1.4.2` let me know if it works as expected. Thank @memery-imb for the code :wink:
