### ISSUE TITLE
Broken under SublimeLinter-flake8

### ISSUE THREAD

**Issue by danpalmer** [gforcada/flake8-builtins#6]
Commit 628e988459fd827e4960ea82a397a08914a5de23 broke `flake8-builtins` when running in SublimeText under SublimeLinter and SublimeLinter-flake8. This causes flake8 linting to stop working entirely in the editor as an exception is thrown during linting.

```
Traceback (most recent call last):
  File "~/.virtualenvs/linting/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "~/.virtualenvs/linting/lib/python2.7/site-packages/flake8/main.py", line 36, in main
    report = flake8_style.check_files()
  File "~/.virtualenvs/linting/lib/python2.7/site-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "~/.virtualenvs/linting/lib/python2.7/site-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "~/.virtualenvs/linting/lib/python2.7/site-packages/pycodestyle.py", line 1877, in check_files
    runner(path)
  File "~/.virtualenvs/linting/lib/python2.7/site-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "~/.virtualenvs/linting/lib/python2.7/site-packages/pycodestyle.py", line 1608, in check_all
    self.check_ast()
  File "~/.virtualenvs/linting/lib/python2.7/site-packages/pycodestyle.py", line 1555, in check_ast
    for lineno, offset, text, check in checker.run():
  File "~/.virtualenvs/linting/lib/python2.7/site-packages/flake8_builtins.py", line 54, in run
    tree = ast.parse(lines)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
TypeError: expected a readable buffer object
```

I'm not sure exactly what is going wrong here, but apparently dropping the lines added in the commit fixes the issue. I don't want to just make a PR for this though, as I'm sure I'm missing some detail as to why it was added in the first place.

**Comment by danpalmer** [comment]
Also, I've noticed the diff doesn't actually _use_ the new value of `tree` that is causing this issue.

```python
 def run(self):
     tree = self.tree
  
     if self.filename == 'stdin':
         lines = stdin_utils.stdin_get_value().splitlines(True)
         tree = ast.parse(lines)
  
     for statement in ast.walk(self.tree):
        # ...
```

**Comment by danpalmer** [comment]
Ha looks like someone already beat me to it! https://github.com/gforcada/flake8-builtins/pull/5

**Comment by gforcada** [comment]
@danpalmer would you mind trying with the new 0.4 version and report back if it works for you?

**Comment by danpalmer** [comment]
@gforcada assuming the PRs were merged I'm sure it will be working – I've been using my own fork with the PRs merged in for the last 10 days and it has been working fine. Unfortunately I won't have time to verify this further on our codebase for a week or so (but I'm happy to close this as I imagine it's fine).

**Comment by gforcada** [comment]
@danpalmer no problem, just re-open the ticket or create a new one whenever you see a problem.

Thanks for reporting it and provide the patches to fix it!
