### ISSUE TITLE
Uninstalling breaks flake8

### ISSUE THREAD

**Issue by Dreamsorcerer** [gforcada/flake8-builtins#60]
```
> pip3 uninstall flake8-builtins
> flake8
ERROR:flake8.plugins.manager:No module named 'flake8_builtins'
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 158, in load_plugin
    self._load()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 135, in _load
    self._plugin = self.entry_point.load()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'flake8_builtins'
CRITICAL:flake8.plugins.manager:Flake8 failed to load plugin "A00" due to No module named 'flake8_builtins'.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 158, in load_plugin
    self._load()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 135, in _load
    self._plugin = self.entry_point.load()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'flake8_builtins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/application.py", line 380, in _run
    self.initialize(argv)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/application.py", line 363, in initialize
    self.find_plugins()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/application.py", line 199, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 410, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 297, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 408, in load_plugin
    return plugin.load_plugin()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/manager.py", line 165, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "A00" due to No module named 'flake8_builtins'.
```

**Comment by Dreamsorcerer** [comment]
OK, I was able to uninstall it a second time, and then the error went away. So, maybe a bug with pip's uninstall process..

**Comment by Dreamsorcerer** [comment]
Definitely pip, just had the same issue with another plugin.
